In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
df.shape

(5572, 3)

In [ ]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

<h3>Train test split</h3>

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
X_train[:4]

697     Aight, you close by or still down around alex'...
4369    1 I don't have her number and 2 its gonna be a...
1441    Cool breeze... Bright sun... Fresh flower... T...
421      Yes:)from last week itself i'm taking live call.
Name: Message, dtype: object

In [ ]:
type(y_train)

pandas.core.series.Series

In [ ]:
y_train[:4]

697     0
4369    0
1441    0
421     0
Name: spam, dtype: int64

In [ ]:
type(X_train.values)

numpy.ndarray

<h3>Create bag of words representation using CountVectorizer</h3>

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59327 stored elements and shape (4457, 7769)>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X_train_cv.shape

(4457, 7769)

In [ ]:
v.get_feature_names_out()[1771]

'cheating'

In [ ]:
v.vocabulary_

{'aight': 881,
 'you': 7731,
 'close': 1872,
 'by': 1612,
 'or': 5002,
 'still': 6500,
 'down': 2441,
 'around': 1084,
 'alex': 905,
 'place': 5259,
 'don': 2423,
 'have': 3373,
 'her': 3429,
 'number': 4878,
 'and': 966,
 'its': 3791,
 'gonna': 3190,
 'be': 1292,
 'massive': 4396,
 'pain': 5079,
 'in': 3669,
 'the': 6839,
 'ass': 1121,
 'rather': 5600,
 'not': 4850,
 'get': 3127,
 'involved': 3757,
 'if': 3626,
 'that': 6836,
 'possible': 5355,
 'cool': 2027,
 'breeze': 1522,
 'bright': 1528,
 'sun': 6620,
 'fresh': 3003,
 'flower': 2915,
 'twittering': 7118,
 'birds': 1386,
 'all': 914,
 'these': 6857,
 'waiting': 7381,
 'to': 6959,
 'wish': 7562,
 'goodmorning': 3196,
 'amp': 953,
 'nice': 4791,
 'day': 2202,
 'yes': 7714,
 'from': 3026,
 'last': 4043,
 'week': 7462,
 'itself': 3792,
 'taking': 6721,
 'live': 4174,
 'call': 1627,
 'omw': 4957,
 'back': 1212,
 'tampa': 6733,
 'west': 7491,
 'palm': 5084,
 'hear': 3393,
 'what': 7497,
 'happened': 3342,
 'orange': 5006,
 'brings': 153

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.where(X_train_np[0]!=0)

(array([ 881,  905, 1084, 1612, 1872, 2441, 5002, 5259, 6500, 7731]),)

In [ ]:
X_train_np[0][1771]

np.int64(0)

<h3>Train the naive bayes model</h3>

In [ ]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [ ]:
X_test_cv = v.transform(X_test)

<h3>Evaluate Performance</h3>

In [ ]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       965
           1       0.98      0.95      0.96       150

    accuracy                           0.99      1115
   macro avg       0.99      0.97      0.98      1115
weighted avg       0.99      0.99      0.99      1115



### Test

In [ ]:
emails = [
    'Hey mohan, can we get together to watch footbal game tomorrow?',
    'Upto 20% discount on parking, exclusive offer just for you. Dont miss this reward!'
]

emails_count = v.transform(emails)
model.predict(emails_count)

array([0, 1])